/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<
      'index',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account': RouteRecordInfo<
      'account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account-settings': RouteRecordInfo<
      'account-settings',
      '/account-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'assessments': RouteRecordInfo<
      'assessments',
      '/assessments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'attendance': RouteRecordInfo<
      'attendance',
      '/attendance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'attendance-detail': RouteRecordInfo<
      'attendance-detail',
      '/attendance-detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'classes': RouteRecordInfo<
      'classes',
      '/classes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'course': RouteRecordInfo<
      'course',
      '/course',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-teacher': RouteRecordInfo<
      'dashboard-teacher',
      '/dashboard-teacher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'design-system': RouteRecordInfo<
      'design-system',
      '/design-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'event': RouteRecordInfo<
      'event',
      '/event',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'meeting-journal-create': RouteRecordInfo<
      'meeting-journal-create',
      '/meeting-journal/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'my-attendance': RouteRecordInfo<
      'my-attendance',
      '/my-attendance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'permission': RouteRecordInfo<
      'permission',
      '/permission',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports': RouteRecordInfo<
      'reports',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'role': RouteRecordInfo<
      'role',
      '/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'schedule': RouteRecordInfo<
      'schedule',
      '/schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'student-detail': RouteRecordInfo<
      'student-detail',
      '/student-detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'students': RouteRecordInfo<
      'students',
      '/students',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user': RouteRecordInfo<
      'user',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user-variant-2': RouteRecordInfo<
      'user-variant-2',
      '/user-variant-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.vue': {
      routes:
        | 'index'
      views:
        | never
    }
    'pages/account.vue': {
      routes:
        | 'account'
      views:
        | never
    }
    'pages/account-settings.vue': {
      routes:
        | 'account-settings'
      views:
        | never
    }
    'pages/assessments.vue': {
      routes:
        | 'assessments'
      views:
        | never
    }
    'pages/attendance.vue': {
      routes:
        | 'attendance'
      views:
        | never
    }
    'pages/attendance-detail.vue': {
      routes:
        | 'attendance-detail'
      views:
        | never
    }
    'pages/classes.vue': {
      routes:
        | 'classes'
      views:
        | never
    }
    'pages/course.vue': {
      routes:
        | 'course'
      views:
        | never
    }
    'pages/dashboard-teacher.vue': {
      routes:
        | 'dashboard-teacher'
      views:
        | never
    }
    'pages/design-system.vue': {
      routes:
        | 'design-system'
      views:
        | never
    }
    'pages/event.vue': {
      routes:
        | 'event'
      views:
        | never
    }
    'pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'pages/meeting-journal/create.vue': {
      routes:
        | 'meeting-journal-create'
      views:
        | never
    }
    'pages/my-attendance.vue': {
      routes:
        | 'my-attendance'
      views:
        | never
    }
    'pages/permission.vue': {
      routes:
        | 'permission'
      views:
        | never
    }
    'pages/reports.vue': {
      routes:
        | 'reports'
      views:
        | never
    }
    'pages/role.vue': {
      routes:
        | 'role'
      views:
        | never
    }
    'pages/schedule.vue': {
      routes:
        | 'schedule'
      views:
        | never
    }
    'pages/student-detail.vue': {
      routes:
        | 'student-detail'
      views:
        | never
    }
    'pages/students.vue': {
      routes:
        | 'students'
      views:
        | never
    }
    'pages/user.vue': {
      routes:
        | 'user'
      views:
        | never
    }
    'pages/user-variant-2.vue': {
      routes:
        | 'user-variant-2'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
