/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'account-settings': RouteRecordInfo<'account-settings', '/account-settings', Record<never, never>, Record<never, never>>,
    'assessments': RouteRecordInfo<'assessments', '/assessments', Record<never, never>, Record<never, never>>,
    'attendance': RouteRecordInfo<'attendance', '/attendance', Record<never, never>, Record<never, never>>,
    'attendance-detail': RouteRecordInfo<'attendance-detail', '/attendance-detail', Record<never, never>, Record<never, never>>,
    'classes': RouteRecordInfo<'classes', '/classes', Record<never, never>, Record<never, never>>,
    'dashboard-teacher': RouteRecordInfo<'dashboard-teacher', '/dashboard-teacher', Record<never, never>, Record<never, never>>,
    'design-system': RouteRecordInfo<'design-system', '/design-system', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'meeting-journal-create': RouteRecordInfo<'meeting-journal-create', '/meeting-journal/create', Record<never, never>, Record<never, never>>,
    'permission': RouteRecordInfo<'permission', '/permission', Record<never, never>, Record<never, never>>,
    'reports': RouteRecordInfo<'reports', '/reports', Record<never, never>, Record<never, never>>,
    'role': RouteRecordInfo<'role', '/role', Record<never, never>, Record<never, never>>,
    'schedule': RouteRecordInfo<'schedule', '/schedule', Record<never, never>, Record<never, never>>,
    'user': RouteRecordInfo<'user', '/user', Record<never, never>, Record<never, never>>,
    'user-variant-2': RouteRecordInfo<'user-variant-2', '/user-variant-2', Record<never, never>, Record<never, never>>,
  }
}
